### PR TITLE
Add "Mark as Visited" column & tooltip

### PR DESCRIPTION
**Pull request by kristi-h**
There is a tooltip for the searchbar as well as for individual columns, to provide clarification to user on different filters available. I added PoppersProp to offset position of tooltip from the anchor (headerName) and be closer to the ellipses. But the distance varies for each column.. I'm still figuring out how to make the offset more dynamic to the column.

### CODE REVIEW

**Review by jesslane94 — COMMENTED** [review]
Search appears to work well for me, I like how it searches all columns. Love the tooltips! Really cool 👯 Otherwise the only thing for me is that if I mark an appointment as "VISITED", it doesn't persist when I switch pages? If this is going to be worked on in a future PR ignore me otherwise!

Idk if necessary, but maybe in the future we could consider making the mark as visited button not visible cancelled appointments! Also when you hover over the ellipses right now for all the column titles it just says "menu", idk if that can be changed.

**Comment by kristi-h** [comment]
> Search appears to work well for me, I like how it searches all columns. Love the tooltips! Really cool 👯 

Thanks! Yea~ Tim's feedback about adding a tooltip was a good idea!

> Otherwise the only thing for me is that if I mark an appointment as "VISITED", it doesn't persist when I switch pages? 

OHH! Thanks for pointing this out!!
I'll fix this now :D

> Idk if necessary, but maybe in the future we could consider making the mark as visited button not visible cancelled appointments! 

ah, good idea~ sure thing!

> Also when you hover over the ellipses right now for all the column titles it just says "menu", idk if that can be changed.
So that is just a part of the data grid. 
Is it distracting to have the "menu" pop up over the ellipses as well as the headerName tooltip?
If so, I can try to find a way to replace that Menu with the current headerName tooltip msg.

**Comment by jesslane94** [comment]
> > Also when you hover over the ellipses right now for all the column titles it just says "menu", idk if that can be changed.
> So that is just a part of the data grid.
> Is it distracting to have the "menu" pop up over the ellipses as well as the headerName tooltip?
> If so, I can try to find a way to replace that Menu with the current headerName tooltip msg.

It would be nice, but honestly it's not a huge deal to me so I wouldn't like go too crazy into it! But if you have the spoons :D

**Review by tdkent — CHANGES_REQUESTED** [review]
Nice to have the tooltip with the search input so its more obvious how the filtering is working. I'm not sure the other tooltips are really necessary, tbh, and they appear to be adding a lot of bloat in the Grid component.

IMO the "Mark as Visited" column should instead be "Status" and "Need to Visit" should be "Confirmed" (assuming there is an appointment date, which all appointments currently have by default). 

I still think the status should be selectable via a dropdown instead of a button, but this works. Of course, there needs to be a request to the db, but that does not need to be added in this PR.

Also, at this point the "Requested On" column should be replaced with the actual appointment date.

**Comment by kristi-h** [comment]
> Nice to have the tooltip with the search input so its more obvious how the filtering is working. I'm not sure the other tooltips are really necessary, tbh, and they appear to be adding a lot of bloat in the Grid component.

Ahh, I added the other tool tips b/c I wanted to give more clarification in case it was confusing what the purpose of the all filter search bar was compared to the individual filter options. I can get rid of them if you feel like it's intuitive and we don't need them.

> IMO the "Mark as Visited" column should instead be "Status" and "Need to Visit" should be "Confirmed" (assuming there is an appointment date, which all appointments currently have by default).

So right now, I'm keeping them separate so it's obvious to the user who has and hasn't been visited, which feels to me as the most important status. And the status column reflects the automatic changes to status as well as manual overrides  by user. I'll keep it for now to finish this up and show you what I mean. But if you still don't like it, I don't mind getting rid of it.

> I still think the status should be selectable via a dropdown instead of a button, but this works. Of course, there needs to be a request to the db, but that does not need to be added in this PR.

Yes, adding the dropdown for status!

> Also, at this point the "Requested On" column should be replaced with the actual appointment date.

On it!

**Review by tdkent — APPROVED** [review]

**Pull request merged**
