### PR TITLE
Fetch User's Appointment and Cancel Function

### PR DESCRIPTION
**Pull request by tdkent**
#### Main Changes:

- adds "/my-appointments" view
- session email is used to fetch appointment from db
- adds fetch single appt server action
- conditional rendering if user does not have an existing appointment
- render appointment details
- "Cancel Appointment" button
   - conditionally rendered based on appt status
   - opens a confirmation modal
- adds cancel appt server action
- adds cancel appt patch route in backend that sets status to "Cancelled"
  - returns an error if the status is "Cancelled" or "Visited" 
- server side errors are rendered in a toast
- on success the path is revalidated and renders updated appt data

#### Other Changes
- the user's session is used to determine their id and auto-load email into request appt form
- added conditional rendering to Request Appt and My Appts views to prevent crashes if user is not logged in
- adds error toast component
- changes backend "form" naming to "appointments" and consolidates files

#### Left To Do
- use session to check google id and email when submitting/fetching forms
- add authorization middleware to prevent users who are not logged in from accessing Appt views
- prevent users with existing appointments from making new appointments
  - unless status is "Cancelled"?

### CODE REVIEW

**Review by jesslane94 — COMMENTED** [review]
Only thing I really have to comment on is when I make an appointment, then cancel it, it does show me the one appointment I cancelled, but not any pending ones if I try to make a new appointment after, which is slightly confusing since I get a success message when making that second request! And I know the request does go through because I can see it on the admin side. Wasn't sure if that was how you wanted it to behave, and if not, could just address that in another branch probably and then approve this one? (everything else I worked as intended for me at least)

**Comment by tdkent** [comment]
Correct, at the moment it is still possible to create multiple appointments without any restrictions, and the fetch request is not necessarily fetching the most recently created appointment if you do. I thought about adding that in, but this branch is already doing too much.

**Comment by jesslane94** [comment]
> Correct, at the moment it is still possible to create multiple appointments without any restrictions, and the fetch request is not necessarily fetching the most recently created appointment if you do. I thought about adding that in, but this branch is already doing too much.

makes sense! ill approve :]

**Review by jesslane94 — APPROVED** [review]
nice work, got a lot more views & functionality between the resident and their appointments.

**Pull request merged**
