### PR TITLE
Full autocomplete

### PR DESCRIPTION
**Pull request by DalySoftware**
Allows autocompleting from the full LA City address dataset.

This uses some pre-setup on the server side. We wrote a function to convert the giant 300MB json file into a 70 MB SQLite database. I've uploaded this file to the backend at /home/www/addresses.db.

The server then provides an autocomplete API using this database. The client has been updated to use this instead of using LA City directly.

The address data includes Lat and Long, so this can also replace the need for Google's geocoding if we update that.

> [!NOTE]
> Developers need to: 
> - Update the client `SERVER_URL` environment variable to `NEXT_PUBLIC_SERVER_URL`
>   - The old LA City variables can also be deleted
> - Download the [address database](https://file.io/qXbhWRKbqOLD) to their `server` folder

### CODE REVIEW

**Comment by DalySoftware** [comment]
If this gets merged after other outstanding PRs, I'll need to re-copy that file manually once

**Comment by kristi-h** [comment]
I keep getting fetch errors with several of the addresses.
And sometimes, it doesn't seem to like my phone number.
Screenshot 2024-12-03 at 4 46 35 PM

Also- is there an address I can check for in the full address file vs. the mini version we were fetching from earlier?
Just glancing at the addresses, they seem similar to the options popping up before the change..

**Comment by DalySoftware** [comment]
> I keep getting fetch errors with several of the addresses. And sometimes, it doesn't seem to like my phone number. Screenshot 2024-12-03 at 4 46 35 PM
> 
> Also- is there an address I can check for in the full address file vs. the mini version we were fetching from earlier? Just glancing at the addresses, they seem similar to the options popping up before the change..

Form submission hasn't changed, I believe this would be an example of the bugginess I described in planning.

There was no static set of addresses before, it was pulling an arbitrary 500 from the API

**Comment by tdkent** [comment]
> And sometimes, it doesn't seem to like my phone number.

Can you provide a more helpful description of the issue you are running into with the phone number?

**Comment by kristi-h** [comment]
> Can you provide a more helpful description of the issue you are running into with the phone number?

Haha sorry, that wasn't very helpful. I thought I took two screenshots of each error (The phone number error occurred first on its own) but I don't think it was captured. I was trying to repro it again, and I think it's just a stale error msg for the phone number not clearing, even after the phone number gets re-entered in the right format. But the address fetching error keeps persisting.

**Review by tdkent — CHANGES_REQUESTED** [review]
Nice work on getting this feature up and running. I never thought of putting the addresses into a sqlite db, that's a great idea! I tested the feature out using the address Kris was having an issue with, and with some other addresses, and never got any fetch errors, and was sometimes able to submit the form. However, I did run into some notable issues:

- Unless I type extremely slowly, the form is very sluggish to catch up with my keystrokes and would take 25-30 seconds to finish the filter and fetch process and display the address
- Clicking on an address seems to cause another filtering process, and the dropdown displays the same address duplicated many times
- Selecting an address does not close the dropdown, so its hard to tell if the selection has worked (although in most cases it actually has correctly selected the address)
- With the sheer number of fetch calls that are happening, its quite easy to overload the browser and get "insufficient resource" errors. The only time I was able to recreate Kris's error (`"address" is not allowed to be empty`) was when this had occurred. Typing quickly and deleting typos in particular seemed to cause this issue.

https://github.com/user-attachments/assets/c24b4554-9965-44b5-9340-1da923c7008b

Screenshot 2024-12-03 at 5 48 29 PM

Sorry for the poor quality video but GitHub would only allow < 10MB file uploads

**Comment by DalySoftware** [comment]
I thought there was a default debounce, but it was apparently 0. I've set it to 200ms. This cuts down requests a lot.

There was also a (probably existing) issue where the autocompleter was being duplicated in the case that you:
1. Select an address
2. Start entering a new address

I think that's how you were able to see such extreme slowdowns. And I think my last commit fixes it.
It's pretty responsive for me. I do have a fairly new CPU so let me know how it is for you.

Also selecting an address does close the dropdown for me? Possible that it was being so slow before that it didn't seem to.

**Review by tdkent — APPROVED** [review]
The debouncer seems to have cleared up the lag, even when I'm typing quickly its responsive. Lag was probably also causing the issue where selecting an address did not close the dropdown, as that is no longer an issue either. I'm also not seeing issues with duplicate addresses anymore. Impressive work!

For reference, I'm using a Macbook Pro with an Apple M2 Pro chip, so I don't know that it what an issue with raw computing power. An issue with Chrome maybe?

**Comment by tdkent** [comment]
>  I was trying to repro it again, and I think it's just a stale error msg for the phone number not clearing, even after the phone number gets re-entered in the right format. But the address fetching error keeps persisting.

Ah, okay. We did leave the frontend error handling in a rough state. I'll have to revisit that.

**Pull request merged**
