### PR TITLE
moved landingPage code to index.

### PR DESCRIPTION
**Pull request by jesslane94**
moved landing page code to home page, removed landingPage folder.

### CODE REVIEW

**Review by tdkent — CHANGES_REQUESTED** [review]
The migration looks fine, glad to see we have a proper landing page now. There is an error in **signInCard.jsx** that should be fixed while this is being worked on. The component is CSR and async, which is causing this error:

```
async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
```

Unless the component has to be async that keyword should be removed, but also is there a reason for the component to be CSR other than using the MUI theme in the header?

**Comment by jesslane94** [comment]
> The migration looks fine, glad to see we have a proper landing page now. There is an error in **signInCard.jsx** that should be fixed while this is being worked on. The component is CSR and async, which is causing this error:
> 
> ```
> async/await is not yet supported in Client Components, only Server Components. This error is often caused by accidentally adding `'use client'` to a module that was originally written for the server.
> ```
> 
> Unless the component has to be async that keyword should be removed, but also is there a reason for the component to be CSR other than using the MUI theme in the header?

I'll try taking this out and seeing what happens. I think I know what CSR means with context, but I want to make sure with you! But I don't think it's necessary for it to be

**Comment by tdkent** [comment]
> I think I know what CSR means with context, but I want to make sure with you! But I don't think it's necessary for it to be

Ah, sorry. Client side rendered (as opposed to SSR - server side rendered)

**Comment by jesslane94** [comment]
> > I think I know what CSR means with context, but I want to make sure with you! But I don't think it's necessary for it to be
> 
> Ah, sorry. Client side rendered (as opposed to SSR - server side rendered)

no worries! i assumed right i guess. I removed the async and it appears to work fine?!

**Review by tdkent — APPROVED** [review]

**Pull request merged**
