### PR TITLE
Address validation

### PR DESCRIPTION
**Pull request by adbshiau**

### CODE REVIEW

**Comment by zuweeali** [comment]
Validated

**Comment by zuweeali** [comment]
-  validated

**Review by DalySoftware — DISMISSED** [review]
Looks good as a first pass 👍 

Only question is should some of the fields be marked as required?

I guess we might want to improve in future to validate automatically on stop typing or form submit instead of needing a button.

**Comment by tdkent** [comment]
I suggest wrapping the address inputs into a container with a header such as "Address" so its clearer what the inputs are, and that they are a group. 

The inputs should be more adaptive to smaller screen sizes. Having them in a row makes them pretty much unusable on a mobile device. For now, not a big deal.

Also agree with Chris that we should mark inputs as required (this should be applied to the whole form, though). 

Awesome work overall!

**Review by tdkent — APPROVED** [review]

**Pull request merged**
