### PR TITLE
Customize signin

### PR DESCRIPTION
**Pull request by jesslane94**
-Should route any user to the sign in card if they are not logged in, and then should route people to sign in after logout. but of course will need to update with new styling after merge.
-for some reason the photo stopped showing up, if it is the same for you I will have to look into that more. I've tried messing around with it, but can't figure it out. May need to set up a meeting to pick yalls brains about that.

### CODE REVIEW

**Comment by tdkent** [comment]
I can fix the conflict. I deleted the `NavElements` component and moved the code into `Nav`

**Comment by jesslane94** [comment]
> I can fix the conflict. I deleted the `NavElements` component and moved the code into `Nav`

thank you!

**Comment by DalySoftware** [comment]
Is this an improvement? It looks worse than main on mine. I dunno if an image is failing to load

image

**Comment by DalySoftware** [comment]
If you check the network calls you can see that the request to `/solar_panels.jpg` is transforming into `/signIn?callbackUrl=%2Fsolar_panels.jpg`. This tells us that it's being caught be the auth boundary.

I've pushed a rough commit for preventing this. Feel free to adjust

**Comment by jesslane94** [comment]
> If you check the network calls you can see that the request to `/solar_panels.jpg` is transforming into `/signIn?callbackUrl=%2Fsolar_panels.jpg`. This tells us that it's being caught be the auth boundary.
> 
> I've pushed a rough commit for preventing this. Feel free to adjust

I thought I replied to this the other day, but thank you!

**Review by DalySoftware — APPROVED** [review]

**Pull request merged**
